#!/bin/bash
# scripts by adi1090x

## Get data
cache_dir="$HOME/.cache/eww/music_player"
cache_background="${cache_dir}/background_color"
cache_indicator="${cache_dir}/indicator_color"
text_color="${cache_dir}/text_color"
STATUS="$(playerctl status)"
COVER="$(playerctl metadata --format "{{ mpris:artUrl }}")"
MUSIC_DIR="$HOME/Music"
TITLE="$(playerctl metadata --format "{{ title }}")"
ARTIST="$(playerctl metadata --format "{{ artist }}")"
LENGTH="$(playerctl metadata --format "{{ duration(mpris:length) }}")"
CURRENT="$(playerctl metadata --format "{{ duration(position) }}")"
PLAYER="$(playerctl metadata --format "{{playerName}}")"
## Get player name
get_player() {
	if [[ -z "$PLAYER" ]]; then
		echo "-"
	else
		echo "$PLAYER"
	fi
}

## Get status
get_status() {
	if [[ $STATUS == "Playing" ]]; then
		echo "images/icons/music/play-button.png"
	else
		echo "images/icons/music/pause-button.png"
	fi
}


## Get song title
get_song() { 
	if [[ -z "$TITLE" ]]; then
		echo "No player avalaible"
	else
		echo "$TITLE"
	fi	
}

## Get artist
get_artist() {
	if [[ -z "$ARTIST" ]]; then
		echo ""
	else
		echo "$ARTIST"
	fi	
}

## Get time
get_time() {
	if [[ -z "$CURRENT" ]]; then
		echo ""
	else
		echo "$CURRENT"
	fi	
}

get_time_length() {
	if [[ -z "$LENGTH" ]]; then
		echo ""
	else
		echo "$LENGTH"
	fi	
}


## Get cover
get_cover() {
	if [[ -z "$TITLE" ]]; then
		echo "images/icons/music/off_player.png"
	else
		echo "$COVER"
	fi
}

## Get percent

get_percent(){
	PLAYER_LENGTH="$(playerctl metadata --format "{{ mpris:length }}")"
	PLAYER_CURRENT="$(playerctl metadata --format "{{ position }}")"
	PERCENT=$((($PLAYER_CURRENT * 100) / $PLAYER_LENGTH))
	if [[ -z "$LENGTH" ]]; then
		echo "0"
	else
		echo "$PERCENT"
	fi	
}

## Get Colors
get_color_1(){
	cat "$text_color"
}

get_color_2(){
	cat "$cache_background"
}

get_color_3(){
	cat "$cache_indicator"
}



## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--player" ]]; then
	get_player
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ltime" ]]; then
	get_time_length
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--cover_player" ]]; then
	get_cover_player
elif [[ "$1" == "--percent" ]]; then
	get_percent
elif [[ "$1" == "--color_text" ]]; then
	get_color_1
elif [[ "$1" == "--color_background" ]]; then
	get_color_2
elif [[ "$1" == "--color_indicator" ]]; then
	get_color_3
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
fi